// import { z } from 'zod';
// const orderStatusEnum = z.enum( ['pending', 'preparing', 'completed', 'served', 'cancelled']); // Update with the actual status values.


// export const orderValidator = z.object({
//   order_id: z.number().int(), // Assuming order_id is auto-generated, so you may not need to validate it on creation
//   user_id: z.number().int().min(1), // user_id should be an integer and cannot be less than 1
//   order_status: orderStatusEnum.default("pending"), // Default value is 'pending' if not provided
//   total_amount: z.number().gt(0, { message: "Total amount must be greater than zero." }), // Total amount should be a positive decimal number
//   table_number: z.number().int().min(1, { message: "Table number must be greater than 0." }), // Table number must be a positive integer
//   created_at: z.string().optional(), // created_at should be a timestamp string, optional (auto-generated by defaultNow)
//   updated_at: z.string().optional(), // updated_at should be a timestamp string, optional (auto-generated by defaultNow)
// });